### ISSUE TITLE
Unable to start service com.amazonaws.mobileconnectors.s3.transferutility.TransferService

### ISSUE THREAD

**Issue by sibeliusseraphini** [aws/aws-sdk-android#141]
```jsx
Fatal Exception: java.lang.RuntimeException: Unable to start service com.amazonaws.mobileconnectors.s3.transferutility.TransferService@b609229 with null: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getStringExtra(java.lang.String)' on a null object reference
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2904)
       at android.app.ActivityThread.access$2100(ActivityThread.java:149)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1382)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5297)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getStringExtra(java.lang.String)' on a null object reference
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferService.onStartCommand(TransferService.java:180)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2887)
       at android.app.ActivityThread.access$2100(ActivityThread.java:149)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1382)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5297)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
```

SDK version
```gradle
compile 'com.amazonaws:aws-android-sdk-core:2.2.16'
compile 'com.amazonaws:aws-android-sdk-s3:2.2.16'
```

Android 5.0.1
Device: lg_h340

**Comment by fosterzhang** [comment]
@sibeliusseraphini You are probably using version 2.2.11 - 2.2.13. That line number doesn't match in the latest version. Please clean your workspace and rebuild the project.

**Comment by sibeliusseraphini** [comment]
thanks, just upgrade it and it is solved

**Comment by gopal-aressindia** [comment]
@fosterzhang  I am using  following version still getting this crash.
  ```
 compile 'com.amazonaws:aws-android-sdk-core:2.3.6'
    compile 'com.amazonaws:aws-android-sdk-cognito:2.3.6'
    compile 'com.amazonaws:aws-android-sdk-s3:2.3.6'
```

**Crash-log:**

**Comment by anjalsan** [comment]
I'm still getting

```
    implementation 'com.amazonaws:aws-android-sdk-core:2.4.2'
    implementation 'com.amazonaws:aws-android-sdk-s3:2.4.2'
    implementation 'com.amazonaws:aws-android-sdk-cognito:2.4.2'

```

Fatal Exception: java.lang.RuntimeException
Unable to start service com.amazonaws.mobileconnectors.s3.transferutility.TransferService@416bda10 with Intent { cmp=in.okcredit.merchant/com.amazonaws.mobileconnectors.s3.transferutility.TransferService }: java.lang.NullPointerException
