### ISSUE TITLE
Failed to integrate User pool with Cognito Identity

### ISSUE THREAD

**Issue by krasystem** [aws/aws-sdk-android#222]
I am getting the following error when add "User Pool" authentication token in Cognito Identity

Caused by: com.amazonaws.services.cognitoidentity.model.NotAuthorizedException: Invalid login token. Issuer doesn't match providerName (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: NotAuthorizedException; Request ID: a5ef69d2-b94d-11e6-920d-518c0b562ad5)

I followed the setps from the link http://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-integrating-user-pools-with-identity-pools.html

below is the code to authorize user pool with Cognito Identity

```
private AuthenticationHandler authenticationHandler = new AuthenticationHandler() {		
		@Override
		public void onSuccess(CognitoUserSession userSession, CognitoDevice device) {	
			//Sync User pool login in Cognito
			syncCognitoIdentityLogin(userSession);			
		}		
		@Override
		public void onFailure(Exception e) {
			// handle error
		}
		
		@Override
		public void getMFACode(MultiFactorAuthenticationContinuation arg0) {			
		}
		
		@Override
		public void getAuthenticationDetails(AuthenticationContinuation continuation,
				String userName) {			
			//set authentication details
			AuthenticationDetails authenticationDetails = new AuthenticationDetails(userName, "12345678", null);
	        continuation.setAuthenticationDetails(authenticationDetails);
	        continuation.continueTask();
		}		
		@Override
		public void authenticationChallenge(ChallengeContinuation arg0) {			
		}
	};

private void syncCognitoIdentityLogin(final CognitoUserSession session){
		
         new AsyncTask<Void, Void, Void>() {
			@Override
			protected Void doInBackground(Void... params) {				
				 Map<String, String> logins = cachingCredentialsProvider.getLogins();

		         if(logins == null) {
		             logins = new HashMap<String, String>();
		         }
		         logins.put("cognito-idp." + Regions.US_EAST_1 + ".amazonaws.com/" + USER_POOL_ID, session.getIdToken().getJWTToken());
		         cachingCredentialsProvider.setLogins(logins);
		         cachingCredentialsProvider.refresh();		         
		         
		         
		         // to get Identity ID
		         String identityID = cachingCredentialsProvider.getIdentityId();
		         
		        
		         Log.i(TAG, "Identity ID=" + identityID );

				 return null;
			}
		}.execute();		
        Log.i(TAG, " Cognito Login sync successfully for session " + session.getIdToken().getJWTToken());
	}
```

Also added the User pool client Id in Identity authentication provider

**Comment by jbailey2010** [comment]
One common thing that has tripped people up is which client id is used. Is the client id you input to your identity pool the same one you're using to sign that user in?

**Comment by karthiksaligrama** [comment]
i'm assuming this issue is resolved. Please reopen/ comment if otherwise

**Comment by shabana0508** [comment]
> 
> 
> One common thing that has tripped people up is which client id is used. Is the client id you input to your identity pool the same one you're using to sign that user in?

i have created new user in uerpool after updating poolId in App, Still getting same error

**Comment by shabana0508** [comment]
Can you please suggest something ?

**Comment by shabana0508** [comment]
@jbailey2010 
i have updated poolId and created new user in userpool still I am facing same issue. Can you please suggest me something?

**Comment by desokroshan** [comment]
@shabana0508 Thanks for reaching out. Do you mind opening a new issue with following details:
1.  Steps to reproduce the issue
2. Stack trace you are seeing. 
Please elaborate on your use case and the API you are using. If this is your first time using authentication with AWS, we recommend using [AWSMobileClient](https://aws-amplify.github.io/docs/android/authentication). Please give it a try if you haven't already.
