### ISSUE TITLE
AWSIotMqttManager constructor does not accept endpoint in cn-north-1 region

### ISSUE THREAD

**Issue by a1exwang** [aws/aws-sdk-android#337]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
  - AWS IoT

* In what version of SDK are you facing the problem?
```    
    compile 'com.amazonaws:aws-android-sdk-core:2.4.7
    compile 'com.amazonaws:aws-android-sdk-s3:2.4.7
    compile 'com.amazonaws:aws-android-sdk-iot:2.4.7
```
* Is the issue limited to Simulators / Actual Devices?
  - No

* Can your problem be resolved if you bump to a higher version of SDK?
  - No. I read the code in the latest version https://github.com/aws/aws-sdk-android/commit/3876d78116f5f73be92905d1774230aa34928e0f, the problem still exists.

* Is this problem related to specific Android/OS version?
  - No

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
```
        new AWSIotMqttManager(clientId, "xxxxxxxx.iot.cn-north-1.amazonaws.com.cn");
```
* Please include a stacktrace if applicable.
```
09-07 13:55:23.320 3480-3480/a1ex.wang.awsiottest E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: a1ex.wang.awsiottest, PID: 3480
                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{a1ex.wang.awsiottest/a1ex.wang.awsiottest.MainActivity}: java.lang.IllegalArgumentException: Bad endpoint format.  Expected XXXXXX.iot.[region].amazonaws.com.
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2666)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
                                                                        at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
                                                                     Caused by: java.lang.IllegalArgumentException: Bad endpoint format.  Expected XXXXXX.iot.[region].amazonaws.com.
                                                                        at com.amazonaws.mobileconnectors.iot.AwsIotEndpointUtility.validateIotEndpoint(AwsIotEndpointUtility.java:58)
                                                                        at com.amazonaws.mobileconnectors.iot.AwsIotEndpointUtility.getAccountPrefixFromEndpont(AwsIotEndpointUtility.java:83)
                                                                        at com.amazonaws.mobileconnectors.iot.AWSIotMqttManager.<init>(AWSIotMqttManager.java:520)
                                                                        at a1ex.wang.awsiottest.MainActivity.onCreate(MainActivity.kt:59)
                                                                        at android.app.Activity.performCreate(Activity.java:6682)
                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727) 
                                                                        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                        at android.os.Looper.loop(Looper.java:154) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6121) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779) 
```

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by kvasukib** [comment]
Hello @a1exwang, 

The endpoint you have passed in is wrong.

 new AWSIotMqttManager(clientId, "xxxxxxxx.iot.cn-north-1.amazonaws.com.cn");

should be

 new AWSIotMqttManager(clientId, "xxxxxxxx.iot.cn-north-1.amazonaws.com");

**Comment by a1exwang** [comment]
AWS China confirms it as a bug..

**Comment by kvasukib** [comment]
Sorry for the inconvenience caused. We released 2.6.6 that fixes this issue. Can you check it out?

**Comment by pwa16000** [comment]
Hi,

I tried 2.6.6 recently, the Exception does not exist anymore, but still can't connect to AWS IoT.

The sample program I run was https://github.com/awslabs/aws-sdk-android-samples/tree/master/AndroidPubSub. with similar configuration, I can connect to AWS IoT us-west-2 region, but for cn-north-1. it always failure.
===============================
 git diff HEAD
diff --git a/AndroidPubSub/build.gradle b/AndroidPubSub/build.gradle
....................................
diff --git a/AndroidPubSub/src/com/amazonaws/demo/androidpubsub/PubSubActivity.java b/AndroidPubSub/src/com/amazonaws/demo/androidpubsub/PubSubActivity
index 04410f7..19bf059 100644
--- a/AndroidPubSub/src/com/amazonaws/demo/androidpubsub/PubSubActivity.java
+++ b/AndroidPubSub/src/com/amazonaws/demo/androidpubsub/PubSubActivity.java
@@ -49,15 +49,15 @@ public class PubSubActivity extends Activity {

     // IoT endpoint
     // AWS Iot CLI describe-endpoint call returns: XXXXXXXXXX.iot.<region>.amazonaws.com
-    private static final String CUSTOMER_SPECIFIC_ENDPOINT = "a2ehi1nzc4rs7q.iot.us-west-2.amazonaws.com";
+    private static final String CUSTOMER_SPECIFIC_ENDPOINT = "anxibkbb9j48a.iot.cn-north-1.amazonaws.com.cn";
     // Cognito pool ID. For this app, pool needs to be unauthenticated pool with
     // AWS IoT permissions.
-    private static final String COGNITO_POOL_ID = "us-west-2:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
+    private static final String COGNITO_POOL_ID = "cn-north-1:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"; 
     // Name of the AWS IoT policy to attach to a newly created certificate
-    private static final String AWS_IOT_POLICY_NAME = "MyRaspberryPiPolicy";
+    private static final String AWS_IOT_POLICY_NAME = "MyRaspberryPiNum01Policy";

     // Region of AWS IoT
-    private static final Regions MY_REGION = Regions.US_WEST_2;
+    private static final Regions MY_REGION = Regions.CN_NORTH_1;
     // Filename of KeyStore file on the filesystem
     private static final String KEYSTORE_NAME = "iot_keystore";
     // Password for the private key in the KeyStore
===============================

I tried use manual build keystore to access, I can't connect to AWS IoT cn-north-1 region also. 

The way I do is: store private key and certificate to 2 strings, then create keystore, then use it to connect. but failed always.
===============================
     try {
            if (AWSIotKeystoreHelper.isKeystorePresent(keystorePath,keystoreName)){
                if(AWSIotKeystoreHelper.keystoreContainsAlias(certificateId,keystorePath,keystoreName,keystorePassword)){
                    AWSIotKeystoreHelper.deleteKeystoreAlias(certificateId,keystorePath,keystoreName,keystorePassword);
                }
            }
        } catch (Exception e) {
            Log.e(LOG_TAG, "An error occurred delete alias from keystore.", e);
        }
        AWSIotKeystoreHelper.saveCertificateAndPrivateKey(certificateId, certPem, keyPem,keystorePath,keystoreName,keystorePassword);
=====================================

Could you please help have a check?

Best regard
Philip

**Comment by kvasukib** [comment]
Hi @pwa16000,

Can you try upgrading to 2.6.7 and check if it's fixed?

**Comment by a1exwang** [comment]
Yes, It is working. Thanks!
