### ISSUE TITLE
Transfer utility doesn't resume upload after network enable if started without connection on Android 8

### ISSUE THREAD

**Issue by FilenkovMaxim** [aws/aws-sdk-android#528]
* What service are you using?
Transfer utility upload.

* In what version of SDK are you facing the problem?
com.amazonaws:aws-android-sdk-s3:2.6.30

* Is the issue limited to Simulators / Actual Devices?
Actual device: Sony G3412 

* Can your problem be resolved if you bump to a higher version of SDK?
No

* Is this problem related to specific Android/OS version?
I see it on Android 8.

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
- Switch on Airplane Mode
- Start upload
- Switch Airplane Mode off

* Please include a stacktrace if applicable.
com.amazonaws.AmazonClientException: Unable to execute HTTP request: Unable to resolve host "s3.eu-central-1.amazonaws.com": No address associated with hostname
    	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:441) ~[na:0.0]
    	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212) ~[na:0.0]
    	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4659) ~[na:0.0]
    	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1752) ~[na:0.0]
    	at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion(UploadTask.java:219) ~[na:0.0]
    	at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:93) ~[na:0.0]
    	at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:49) ~[na:0.0]
    	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:0.0]
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) ~[na:0.0]
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) ~[na:0.0]
    	at java.lang.Thread.run(Thread.java:764) ~[na:0.0]
    Caused by: java.net.UnknownHostException: Unable to resolve host "s3.eu-central-1.amazonaws.com": No address associated with hostname
    	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:111) ~[na:0.0]
    	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:90) ~[na:0.0]
    	at java.net.InetAddress.getAllByName(InetAddress.java:792) ~[na:0.0]
    	at com.android.okhttp.Dns$1.lookup(Dns.java:39) ~[na:0.0]
    	at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:175) ~[na:0.0]
    	at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:141) ~[na:0.0]
    	at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:83) ~[na:0.0]
    	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:174) ~[na:0.0]
    	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126) ~[na:0.0]
    	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95) ~[na:0.0]
    	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:301) ~[na:0.0]
    	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:244) ~[na:0.0]
    	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:473) ~[na:0.0]
    	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127) ~[na:0.0]
    	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262) ~[na:0.0]
    	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218) ~[na:0.0]
    	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(Unknown Source:0) ~[na:0.0]
    	at com.amazonaws.http.UrlHttpClient.writeContentToConnection(UrlHttpClient.java:162) ~[na:0.0]
    	at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:75) ~[na:0.0]
    	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:371) ~[na:0.0]

It seems to me that you try to connect too early when the network is not ready yet.

**Comment by FilenkovMaxim** [comment]
@kvasukib Yes, state is WAITING_FOR_NETWORK

**Comment by kvasukib** [comment]
@FilenkovMaxim That's the expected behavior. When the network is offline and if you try to start an upload, the TransferUtility puts the state of the transfer to `WAITING_FOR_NETWORK`. When network comes back online, the TransferService gets a notification and it resumes the transfers that were in `WAITING_FOR_NETWORK` state.

**Comment by kvasukib** [comment]
@FilenkovMaxim Thank you for the feedback. TransferService receives a broadcast from Android OS when the network comes back online. To resume the transfers, we load the transfers from the database that are in WAITING_FOR_NETWORK state and we resume the transfers if they are not running.

1) Android is giving the notification early. 
2) TransferService is using the deprecated network callback mechanism
3) Android 8 has imposed limitations on operations in the background.
4) TransferService has a periodic cron job that automatically resumes transfers that are stuck.

For 1) We have log statements in the code that says when the network comes back online and when we resume the transfers. Can you grab these logs and see what's the issue?

For 2) I will file a task internally to move to the new network callback mechanism

For 3) We are in the process of making changes to conform to Android limitations on background operations.

For 4) We are working on to refactor the cron job.

I will post an update when the fixes are released. Meanwhile, if you could grab the log statements, that would be helpful. Thanks!

**Comment by kvasukib** [comment]
@FilenkovMaxim Update: Tasks 3 and 4 are complete. We released 2.7.0 with some major refactoring to the TransferUtility. The summary of the changes can be found in [CHANGELOG](https://github.com/aws/aws-sdk-android/blob/master/CHANGELOG.md) or [Documentation](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/how-to-transfer-files-with-transfer-utility.html#long-running-transfers).

Summary:

Starting version 2.7.0 of the SDK, TransferService logic has been refactored. This service now will be responsible only for monitoring network connectivity changes. When the network goes offline, the transfers that are in progress will be paused. When the network comes back online, the transfers that are paused will be resumed. If you expect your app to perform long-running transfers in the background, you need to initiate the transfers from a background service of your choice.

The TransferService will not be started or stopped by TransferUtility anymore. You have to start TransferService manually from your application. A recommended way is to start the service upon Application startup. One way you can do this is to include the following line in the onCreate method of your app's Application class.

```java
    getApplicationContext().startService(new Intent(getApplicationContext(), TransferService.class));
```

Please upgrade to 2.7.0 and give it a try and let us know any feedback you have.

**Comment by FilenkovMaxim** [comment]
@kvasukib thank you. I tried new 2.7.0 but it still doesn't work in this case.
That what I've seen in logcat

09-25 07:37:30.520 24373-24373/com.dubsapp.devel I/TransferService: Network connectivity changed detected.
09-25 07:37:30.525 24373-24373/com.dubsapp.devel I/TransferService: Network connected: true
09-25 07:37:30.538 24373-24373/com.dubsapp.devel I/TransferService: Network connectivity changed detected.
09-25 07:37:30.547 24373-24373/com.dubsapp.devel I/TransferService: Network connected: true
09-25 07:37:30.579 24373-24442/com.dubsapp.devel E/services.LogsUploadService: [main] LogsUploadService	 #UPLOAD 12 onError: {}
    com.amazonaws.AmazonClientException: Unable to execute HTTP request: Unable to resolve host "s3.eu-central-1.amazonaws.com": No address associated with hostname
    	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:441) ~[na:0.0]
    	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212) ~[na:0.0]
    	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4659) ~[na:0.0]
    	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1752) ~[na:0.0]
    	at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion(UploadTask.java:218) ~[na:0.0]
    	at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:91) ~[na:0.0]
    	at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:48) ~[na:0.0]
    	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:0.0]
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) ~[na:0.0]
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) ~[na:0.0]
    	at java.lang.Thread.run(Thread.java:764) ~[na:0.0]
    Caused by: java.net.UnknownHostException: Unable to resolve host "s3.eu-central-1.amazonaws.com": No address associated with hostname
    	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:111) ~[na:0.0]
    	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:90) ~[na:0.0]
    	at java.net.InetAddress.getAllByName(InetAddress.java:792) ~[na:0.0]
    	at com.android.okhttp.Dns$1.lookup(Dns.java:39) ~[na:0.0]
    	at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:175) ~[na:0.0]
    	at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:141) ~[na:0.0]
    	at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:83) ~[na:0.0]
    	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:174) ~[na:0.0]
    	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126) ~[na:0.0]
    	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95) ~[na:0.0]
    	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:301) ~[na:0.0]
    	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:244) ~[na:0.0]
    	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:473) ~[na:0.0]
    	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127) ~[na:0.0]
    	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262) ~[na:0.0]
    	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218) ~[na:0.0]
    	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(Unknown Source:0) ~[na:0.0]
    	at com.amazonaws.http.UrlHttpClient.writeContentToConnection(UrlHttpClient.java:162) ~[na:0.0]
    	at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:75) ~[na:0.0]
    	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:371) ~[na:0.0]
    	... 10 common frames omitted
09-25 07:38:30.683 2273-2287/? W/ActivityManager: Stopping service due to app idle: u0a301 -13m40s746ms com.dubsapp.devel/com.amazonaws.mobileconnectors.s3.transferutility.TransferService
09-25 07:38:30.697 24373-24373/com.dubsapp.devel I/TransferService: Unregistering the network receiver

P.S. I didn't find how to get more logs.

**Comment by FilenkovMaxim** [comment]
@kvasukib Hello. Do you have news on this issue?
Do you have an example working with android 8 in this scenario?

**Comment by kvasukib** [comment]
@FilenkovMaxim The code that you already have should work on Android 8 (Oreo). We do not rely on a service anymore to start the transfers. Instead the transfers are started directly by TransferUtility without a service. TransferService will be only be used to listen for network connectivity changes. 

https://docs.aws.amazon.com/aws-mobile/latest/developerguide/how-to-transfer-files-with-transfer-utility.html#long-running-transfers

**Comment by FilenkovMaxim** [comment]
Hi, I tried to take a look on your example [here](https://github.com/awslabs/aws-sdk-android-samples/tree/master/S3TransferUtilitySample)
But it didn't work at all. Util.getCredProvider() failed with 
AndroidRuntime: FATAL EXCEPTION Caused by: java.lang.IllegalArgumentException: Cannot create enum from CHANGE_ME value!
Please, check your example.

**Comment by kvasukib** [comment]
@FilenkovMaxim You have to put the right values in Constants.java file. You can see the README.md in the sample application to see how to create a Cognito identity pool and S3 bucket and supply the values (cognito identity pool-ID, cognito identity region, S3 bucket name, S3 bucket region) in the Constants.java file.

Can you do this and try again?

**Comment by FilenkovMaxim** [comment]
@kvasukib thanks, my fault, I didn't read. I'll try.

**Comment by FilenkovMaxim** [comment]
@kvasukib ok, I tried the example, for begin on Android 6.
It doesn't set WAITING_FOR_NETWORK state on wifi lost. It turn to FAILED and doesn't resume upload after connection establish.
And I see error 
```
com.amazonaws.demo.s3transferutility E/UploadPartTask: Encountered error uploading part 
    com.amazonaws.AmazonClientException: Unable to execute HTTP request: Unable to resolve host "s3.eu-central-1.amazonaws.com": No address associated with hostname
```
in logcat 17 times!

**Comment by kvasukib** [comment]
@FilenkovMaxim Thank you for the quick response. Starting 2.7.0 you need to add the following line in your app to start the TransferService. TransferService will not be started automatically by the SDK.

```java
getApplicationContext().startService(new Intent(getApplicationContext(), TransferService.class));
```

One recommended place to add this is in your Application class. Please refer to the [CHANGELOG](https://github.com/aws/aws-sdk-android/releases/tag/release_v2.7.0) and [documentation](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/how-to-transfer-files-with-transfer-utility.html) for more details.

**Comment by FilenkovMaxim** [comment]
@kvasukib I know this, but I told about [this](https://github.com/awslabs/aws-sdk-android-samples/tree/master/S3TransferUtilitySample) example, not my app. Why it doesn't start TransferService? It's strange for sample code, isn't it?
Ok, I'll try to change it.

**Comment by kvasukib** [comment]
@FilenkovMaxim Got it. I tested the sample and it works. When the network is set to offline, the transfers that are in progress and set to WAITING_FOR_NETWORK.

**Comment by FilenkovMaxim** [comment]
@kvasukib but I get that error. I switch off wifi during uploading, then task get the FAILED state and doesn't continue after wifi set available. I run it on Android 6.

**Comment by kvasukib** [comment]
@FilenkovMaxim Did you pull the latest changes made to the S3TransferUtilitySampleApp?

**Comment by FilenkovMaxim** [comment]
@kvasukib I changed only sS3Client initialization
```
sS3Client = new AmazonS3Client(new BasicAWSCredentials(awsAccessKey, awsSecretKey));
sS3Client.setRegion(Region.getRegion(Regions.EU_CENTRAL_1));
```
I use BasicAWSCredentials instead Cognito. I think it doesn't matter? Simple upload with wifi works.

**Comment by kvasukib** [comment]
@FilenkovMaxim I just want to make sure you have https://github.com/awslabs/aws-sdk-android-samples/blob/master/S3TransferUtilitySample/src/com/amazonaws/demo/s3transferutility/MyApplication.java class in the app when you downloaded. The `onCreate` in the `Application` will start the TransferService.

**Comment by kvasukib** [comment]
@FilenkovMaxim I will check and update the AndroidManifest as required. For the error from upload operation, can you post the exception message and stacktrace that you are getting?

**Comment by FilenkovMaxim** [comment]
@kvasukib yes, I will able post these on Monday 15th

**Comment by FilenkovMaxim** [comment]
@kvasukib 
On Android 8

```
10-16 11:24:46.995 32341-32341/com.amazonaws.demo.s3transferutility E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.amazonaws.demo.s3transferutility, PID: 32341
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=0, result=-1, data=Intent { dat=content://com.android.providers.downloads.documents/document/raw:/storage/emulated/0/Download/upload2.zip flg=0x43 }} to activity {com.amazonaws.demo.s3transferutility/com.amazonaws.demo.s3transferutility.UploadActivity}: java.lang.NumberFormatException: For input string: "raw:/storage/emulated/0/Download/upload2.zip"
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4485)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4528)
        at android.app.ActivityThread.-wrap19(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1719)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:206)
        at android.app.ActivityThread.main(ActivityThread.java:6749)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:845)
     Caused by: java.lang.NumberFormatException: For input string: "raw:/storage/emulated/0/Download/upload2.zip"
        at java.lang.Long.parseLong(Long.java:590)
        at java.lang.Long.valueOf(Long.java:804)
        at com.amazonaws.demo.s3transferutility.UploadActivity.getPath(UploadActivity.java:549)
        at com.amazonaws.demo.s3transferutility.UploadActivity.onActivityResult(UploadActivity.java:441)
        at android.app.Activity.dispatchActivityResult(Activity.java:7245)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4481)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4528) 
        at android.app.ActivityThread.-wrap19(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1719) 
        at android.os.Handler.dispatchMessage(Handler.java:108) 
        at android.os.Looper.loop(Looper.java:206) 
        at android.app.ActivityThread.main(ActivityThread.java:6749) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:845)

```
On Android 6 path is null and I see the toast "Could not find the filepath of the selected file"

**Comment by kvasukib** [comment]
@FilenkovMaxim The exception is being thrown from https://github.com/awslabs/aws-sdk-android-samples/blob/master/S3TransferUtilitySample/src/com/amazonaws/demo/s3transferutility/UploadActivity.java#L538. 

Can you check the path of the file you are trying to upload? I can see that it is a downloads document: https://github.com/awslabs/aws-sdk-android-samples/blob/master/S3TransferUtilitySample/src/com/amazonaws/demo/s3transferutility/UploadActivity.java#L588

Since this is coming from the S3TransferutilitySampleApp, you can feel free to change the code in getPath to work with your use-case. You can also submit a PR if you find a bug in the code.

**Comment by FilenkovMaxim** [comment]
@kvasukib I know and I did it before (just hardcode the path). 
On my device the problem is that when an CONNECTIVITY_ACTION event occurs the network is not ready yet and throws Unable to resolve host "s3.eu-central-1.amazonaws.com" exception. It would be better to run the procedure not immediately, but after a couple of seconds.
Another problem is that Android 8+ disallow start service from background, only foreground services are allowed or using JobScheduler. Please, check thread https://stackoverflow.com/q/46445265 for details. Therefore it would be better for me to have public method for run on connect/disconnect instead starting service. Something like checkTransfersOnNetworkReconnect()

**Comment by kvasukib** [comment]
@FilenkovMaxim Sorry for the delayed reply. The delay in the network being ready could be tied to the specific device you are running your app. So I suggest you can create your own service by looking at the TransferService where you can investigate the issue related to the delay. 

For the background limitations, you can use the pause/resume methods provided in TransferUtility. You need to query the database for transfers that are pending due to network disconnect and call pause on each of them. Similarly query the transfers that were paused and resume each of the transfer when the network comes back online. 

See https://github.com/aws/aws-sdk-android/blob/master/aws-android-sdk-s3/src/main/java/com/amazonaws/mobileconnectors/s3/transferutility/TransferService.java. I would be happy to review your changes if necessary.

**Comment by DaveCunninghamICT** [comment]
@kvasukib We are seeing a similar problem with files not uploading after being offline and than going online. The AWS iOS libraries had the same issue weeks ago but are now working properly. In issue #517, you commented around Sept 20th about a refactored library and a new call. Are there any other changes we need to know about?

**Comment by kvasukib** [comment]
@DaveCunninghamICT What version of the SDK are you using?
